doctrine:
    dbal:
        #        url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  "%database_charset%"
                #                mapping_types:
                #                    bit: boolean
                default_table_options:
                    charset: "%database_charset%"
                    collate: "%database_collation%"