services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Services:
  CourseHub\Course\Application\Create\CreateCourseHandler:
  CourseHub\Course\Application\Create\CreateCourseTokenHandler:
  CourseHub\Course\Application\Create\CreateCourseResourceHandler:
  CourseHub\Course\Application\Create\CreateCompletionHandler:
  CourseHub\Course\Application\Update\UpdateCourseHandler:
  CourseHub\Course\Application\Update\UpdateCourseResourceHandler:
  CourseHub\Course\Application\CourseValidator:
  CourseHub\Course\Application\CourseResourceValidator:
  CourseHub\Course\Application\CourseWriter:
    class: CourseHub\Course\Infrastructure\DbalCourseWriter
  CourseHub\Course\Application\CourseReader:
    class: CourseHub\Course\Infrastructure\DbalCourseReader
  CourseHub\Course\Application\CourseTokenWriter:
    class: CourseHub\Course\Infrastructure\DbalCourseTokenWriter
  CourseHub\Course\Application\CourseTokenReader:
    class: CourseHub\Course\Infrastructure\DbalCourseTokenReader
  CourseHub\Course\Application\CourseCompletionWriter:
    class: CourseHub\Course\Infrastructure\DbalCourseCompletionWriter
  CourseHub\Course\Application\CourseCompletionReader:
    class: CourseHub\Course\Infrastructure\DbalCourseCompletionReader
  CourseHub\Course\Application\CourseResourceWriter:
    class: CourseHub\Course\Infrastructure\DbalCourseResourceWriter
  CourseHub\Course\Application\CourseResourceReader:
    class: CourseHub\Course\Infrastructure\DbalCourseResourceReader